# NumPy

In [1]:
import numpy as np

## Array basics

First we create a 2-dimensional array (an array with 2 axes).

In [2]:
my_array = np.array([[1, 2], [3, 4], [5, 6]])
my_array

array([[1, 2],
       [3, 4],
       [5, 6]])

Number of dimensions

In [3]:
my_array.ndim

2

The shape is the length of each axis.

In [4]:
my_array.shape  # Three rows, teo columns

(3, 2)

The total number of elements

In [5]:
my_array.size

6

Array size in bytes.

In [6]:
my_array.nbytes

24

Type of array

In [7]:
my_array.dtype

dtype('int32')

We can change dtype. By default a newly allocated array is returned.

In [8]:
my_array.astype(float).dtype

dtype('float64')

By default casting is unsafe, which may have consequences.

In [9]:
my_array.astype(bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Safe casting can be forced.

In [10]:
try:  # to make bad casting in-place.
    my_array.astype(bool, casting='safe', copy=False)
except TypeError as error:
    print(error)
my_array

Cannot cast array from dtype('int32') to dtype('bool') according to the rule 'safe'


array([[1, 2],
       [3, 4],
       [5, 6]])

## Indexing

Indexes operate along any axis.

In [11]:
my_array[0]  # First row. Equivalent to my_array[0, :]

array([1, 2])

Colon slicing is used take multiple elements along the current axis

In [12]:
my_array[:, 0]  # All rows, first column

array([1, 3, 5])

In [13]:
my_array[:2, 0]  # Two first rows, first column

array([1, 3])

You may select along all axes at the same time

In [14]:
my_array[1, 0]  # Second row, first column.

3

In [15]:
my_array[[0, 1], 0]  # First + second row, first column

array([1, 3])

In [16]:
my_array[[0, 1], [1, 0]]  # Second element of first row + first element of second row

array([2, 3])

### Logical indexing

Numpy supports indexing using boolean arrays.

In [17]:
are_first_column = [True, False]
my_array[:, are_first_column]

array([[1],
       [3],
       [5]])

## Linear algebra

Transpose matrix

In [18]:
my_array.T  # equivalent to np.transpose(my_array)

array([[1, 3, 5],
       [2, 4, 6]])

Matrix multiplications

In [19]:
my_array.T @ my_array  # @-operator supported from py3.6, use np.dot(my_array.T, my_array) for older versions.

array([[35, 44],
       [44, 56]])

Numpy `linalg` sub-package 

## Broadcasting

Numpy features broadcasting of many operations which are translated into efficient vectorized operations.

In [20]:
my_array + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [21]:
my_array + [1, 2]  # Add 1 to first column, and 2 to first column

array([[2, 4],
       [4, 6],
       [6, 8]])

To better control which axis the operation is broadcasted to, use arrays of the same number of dimensions.

Then the broadcasting will be matched according to the axis. 

In [22]:
column_array = np.array([[1, 2]])
column_array + my_array

array([[2, 4],
       [4, 6],
       [6, 8]])

In [23]:
try:
    column_array.T + my_array
except ValueError as error:
    print(error)

operands could not be broadcast together with shapes (2,1) (3,2) 


In [24]:
row_array = np.array([[1], [2], [3]])
row_array + my_array

array([[2, 3],
       [5, 6],
       [8, 9]])

### Broadcasted operations

In [25]:
my_array.max()  # Maximum value of array

6

In [26]:
my_array.max(axis=0)  # Max across rows.

array([5, 6])

In [27]:
my_array.min(axis=1)  # Minumum across columns.

array([1, 3, 5])

## Randomness

Numpy `random` sub-package features many functions to create random matrices with different distributions, randomly permute existing arrays or make random subsamples.

In [28]:
np.random.seed(42)  # Seed randomization to make randomization deterministic

random_array = np.random.random(size=(3, 2))  # Uniform random array with 3 rows and 2 columns
random_array

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [29]:
letters = ['a', 'b', 'c', 'd', 'e']
np.random.choice(letters)

'c'

In [30]:
random_integers = np.random.randint(low=0, high=5, size=(2, 3, 4))
random_integers

array([[[2, 4, 3, 2],
        [4, 1, 3, 1],
        [3, 4, 0, 3]],

       [[1, 4, 3, 0],
        [0, 2, 2, 1],
        [3, 3, 2, 3]]])